language: generic
global:
  - CLIVERSION=0.7.2
matrix:
  include:
    - env:
        - BOARD="Seeeduino:samd:zero"
    - env:
        - BOARD="Seeeduino:samd:seeed_wio_terminal"

before_install:
  - sudo apt-get install --reinstall python3-pip
  - sudo apt-get install python3-setuptools
  - python3 -m pip install
  
install:
  - pip3 install ardupy-aip
  - aip

script: 
  - echo "CI Test"
  - aip install  Seeed-Studio/seeed-ardupy-lcd1602
  - aip build 
  
notifications:
  webhooks:
    urls:
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always